<?php

namespace AppBundle\Repository;

/**
 * ShoutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShoutRepository extends \Doctrine\ORM\EntityRepository
{
}
