<?php

namespace AppBundle\Repository;

/**
 * ShoutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShoutRepository extends \Doctrine\ORM\EntityRepository
{
    public function shouts()
    {
        return $this->getEntityManager()
            ->createQuery('
              SELECT u FROM AppBundle:Shout u
              ORDER BY u.createdAt DESC  
            ')
            ->getResult();
    }
}
