# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_db_provider:
            entity:
                class: AppBundle:User
#                property: username
        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            http_basic: ~
            provider: our_db_provider
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                default_target_path: /shout
#                use_forward: true
                csrf_parameter: _csrf_token
#                use_referer: true
            logout:
                path: logout
                target: /login

            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

    access_control:
        - { path: ^/login$, roles: ["IS_AUTHENTICATED_ANONYMOUSLY"] }
        - { path: ^/register$, roles: ["IS_AUTHENTICATED_ANONYMOUSLY"] }
        - { path: ^/, roles: ["IS_AUTHENTICATED_FULLY"] }
#        - { path: ^/admin, roles: ["ROLE_ADMIN"] }
        - { path: ^/shout, roles: ["IS_AUTHENTICATED_FULLY"] }

